### ISSUE TITLE
Laravel 5.7 incompatibility

### ISSUE THREAD

**Issue by DivineOmega** [DivineOmega/password_exposed#25]
It seems this package should not indicate support for v1 of the `guzzle6-adapter` package, because the type of object returned differs between v1 and v2 of the `guzzle6-adapter`.

This causes a compatibility issue with Laravel 5.7

It is caused by Laravel 5.7 requiring the `laravel/nexmo-notification-channel` as standard, which depends on the `nexmo/client` which enforces the use v1 of the `guzzle6-adapter`.

My plan of action is going to be:

* Create a simple PSR18 Guzzle adapter package, that returns an object which implements the correct PSR18 client interface.
* Modify this package to make use of the new PSR18 Guzzle adapter package.

-----

This issue was discovered by @tswestendorp. See https://github.com/DivineOmega/password_exposed/pull/24.

**Comment by DivineOmega** [comment]
If you need to use this package in Laravel 5.7 before this is fixed, feel free to install v2.8.0, which is not affected by this issue.

**Comment by DivineOmega** [comment]
@tswestendorp This is now released as v3.0.1. Would you mind double checking this release is working as expected for you?

**Comment by tswestendorp** [comment]
@DivineOmega Still perfect! Thanks!

**Comment by DivineOmega** [comment]
@tswestendorp Excellent. Thank you for testing.
